version: '3'
services:
  service-discovery:
    platform: linux/amd64
    container_name: service-discovery
    build:
      context: service-discovery
      dockerfile: Dockerfile
    image: byt3social/service-discovery:latest
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - 8761:8761
    networks:
      - b3-social-network
    env_file:
      - .env
  api-gateway:
    platform: linux/amd64
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    image: byt3social/api-gateway:latest
    depends_on:
      - mysql
      - service-discovery
    restart: on-failure
    ports:
      - 8081:8081
    networks:
      - b3-social-network
    env_file:
      - .env
  analise-documental:
    platform: linux/amd64
    container_name: analise-documental
    build:
      context: analise-documental
      dockerfile: Dockerfile
    image: byt3social/analise-documental:latest
    depends_on:
      - api-gateway
    restart: on-failure
    networks:
      - b3-social-network
    env_file:
      - .env
  authentication:
    platform: linux/amd64
    container_name: authentication
    build:
      context: authentication
      dockerfile: Dockerfile
    image: byt3social/authentication:latest
    depends_on:
      - api-gateway
    restart: on-failure
    networks:
      - b3-social-network
    env_file:
      - .env
  prospeccao:
    platform: linux/amd64
    container_name: prospeccao
    build:
      context: prospeccao
      dockerfile: Dockerfile
    image: byt3social/prospeccao:latest
    depends_on:
      - api-gateway
    restart: on-failure
    networks:
      - b3-social-network
    env_file:
      - .env
  acoes-sociais:
    platform: linux/amd64
    container_name: acoes-sociais
    build:
      context: acoes-sociais
      dockerfile: Dockerfile
    image: byt3social/acoes-sociais:latest
    depends_on:
      - api-gateway
    restart: on-failure
    networks:
      - b3-social-network
    env_file:
      - .env
  acompanhamento:
    platform: linux/amd64
    container_name: acompanhamento
    build:
      context: acompanhamento
      dockerfile: Dockerfile
    image: byt3social/acompanhamento:latest
    depends_on:
      - api-gateway
    restart: on-failure
    networks:
      - b3-social-network
    env_file:
      - .env
  logging:
    platform: linux/amd64
    container_name: logging
    build:
      context: logging
      dockerfile: Dockerfile
    image: byt3social/logging:latest
    depends_on:
      - api-gateway
    restart: on-failure
    networks:
      - b3-social-network
    env_file:
      - .env
  front-end:
    platform: linux/amd64
    container_name: front-end
    build:
      context: front-end
      dockerfile: Dockerfile
    image: byt3social/front-end:latest
    depends_on:
      - mysql
      - rabbitmq
      - service-discovery
      - api-gateway
      - authentication
      - prospeccao
      - analise-documental
      - acoes-sociais
      - acompanhamento
      - logging
    ports:
      - 80:80
    networks:
      - b3-social-network
    env_file:
      - .env
  mysql:
    image: "mysql:8.0"
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - b3-social-network
    environment:
      MYSQL_DATABASE: b3_social
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: leandro
      MYSQL_PASSWORD: leandro
      MYSQL_ROOT_PASSWORD:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/
    networks:
      - b3-social-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
networks:
  b3-social-network:
