CREATE DATABASE IF NOT EXISTS ms_authentication;

CREATE DATABASE IF NOT EXISTS ms_prospeccao;

CREATE DATABASE IF NOT EXISTS ms_analise_documental;

CREATE DATABASE IF NOT EXISTS ms_acoes_sociais;

CREATE DATABASE IF NOT EXISTS ms_acompanhamento;